#!/bin/bash

echo "🚀 Deploying Bhushan Charpe's Portfolio to GitHub Pages"
echo "=================================================="
echo "GitHub Username: bhushancharpe15"
echo "Repository: bhushan-charpe-portfolio"
echo "Live URL: https://bhushancharpe15.github.io/bhushan-charpe-portfolio"
echo ""

echo "✅ Your portfolio is ready for deployment!"
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1️⃣  Create GitHub Repository:"
echo "   • Go to https://github.com/new"
echo "   • Repository name: bhushan-charpe-portfolio"
echo "   • Make it PUBLIC"
echo "   • Click 'Create repository'"
echo ""
echo "2️⃣  Push Your Code:"
echo "   • Copy and run these commands:"
echo ""
echo "   git remote add origin https://github.com/bhushancharpe15/bhushan-charpe-portfolio.git"
echo "   git push -u origin main"
echo ""
echo "3️⃣  Enable GitHub Pages:"
echo "   • Go to repository Settings → Pages"
echo "   • Select 'GitHub Actions' as source"
echo "   • Your site will be live automatically!"
echo ""
echo "4️⃣  Your Live Website:"
echo "   🌐 https://bhushancharpe15.github.io/bhushan-charpe-portfolio"
echo ""
echo "🎉 Portfolio Features:"
echo "   ✅ Instagram contact bar (@bhushn.15)"
echo "   ✅ All project links working"
echo "   ✅ Achievement section"
echo "   ✅ GitHub Pages ready"
echo "   ✅ Mobile responsive"
echo "   ✅ SEO optimized"
echo ""
echo "📱 Contact Bar Includes:"
echo "   📧 Email: bhushancharpe135@gmail.com"
echo "   📱 Phone: +91 8767106500"
echo "   💼 LinkedIn: Professional profile"
echo "   📸 Instagram: @bhushn.15"
echo "   💻 GitHub: bhushancharpe15"
echo ""
echo "🚀 Ready to go live! Follow the steps above."
